// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2izrPbvWhBB6C0Lj0kxN755ClpxtaJg',
    appId: '1:222476016561:web:d2e347c97dd13b179e3b90',
    messagingSenderId: '222476016561',
    projectId: 'notamess-90b95',
    authDomain: 'notamess-90b95.firebaseapp.com',
    storageBucket: 'notamess-90b95.appspot.com',
    measurementId: 'G-H1719G9RDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasFOee0ibskZgfPg6830HqbMdUA7LDmo',
    appId: '1:222476016561:android:2cb9be05b3fa3ff59e3b90',
    messagingSenderId: '222476016561',
    projectId: 'notamess-90b95',
    storageBucket: 'notamess-90b95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0lHsX3Q2KY8ZQL7TaT0RtYSSCCDhYPb4',
    appId: '1:222476016561:ios:fdfcd70b92ee0b969e3b90',
    messagingSenderId: '222476016561',
    projectId: 'notamess-90b95',
    storageBucket: 'notamess-90b95.appspot.com',
    iosClientId: '222476016561-3ctina3uud3jubfspuno43r4pqu1gkjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notAMess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0lHsX3Q2KY8ZQL7TaT0RtYSSCCDhYPb4',
    appId: '1:222476016561:ios:fdfcd70b92ee0b969e3b90',
    messagingSenderId: '222476016561',
    projectId: 'notamess-90b95',
    storageBucket: 'notamess-90b95.appspot.com',
    iosClientId: '222476016561-3ctina3uud3jubfspuno43r4pqu1gkjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notAMess',
  );
}
